### PR TITLE
update all dependencies and setup renovate configuration

### LINKED ISSUE #44: Automated depenency updates
There's two main tools we can consider:

- Dependabot (from github)
- Renovate

It seems dependabot is (or was?) active here, but hasn't done much in a while, so maybe it needs more tweaks.

I personally would be inclined to use Renovate, as it comes with a quite cool github bot as well and we have worked with it in the past.

So yeah, basically wondering if people have a tendency to either of those two (or another one). If not, I might just set up a renovate draft and add the bot here for us to do the dependency updates :)

### PR DESCRIPTION
**Pull request by Polymeta**
we have to make sure we enforce the tests to finish before merging, see this here: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging

otherwise renovate can merge in any PR whether it works or not

TODO: how do we version this, do we want to make a major release or minor?

Closes #44

### CODE REVIEW

**Comment by TomSmith27** [comment]
I think the branch protection stuff is set as far as im aware

**Comment by Polymeta** [comment]
ah cool, should we do minor or major release for this?

**Comment by TomSmith27** [comment]
Think we can do a minor release because the only changes to packages that are major are dev ones. So the actual code shouldnt break anything

**Comment by Polymeta** [comment]
okay all done then 👍

**Review by TomSmith27 — APPROVED** [review]

**Pull request merged**
